version: "3.9"

services:
  api:
    container_name: sales-management-api
    
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    
    ports:
      - "8080:8080"
      - "8081:8081"
    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      
     
      - ConnectionStrings__DefaultConnection=Data Source=/data/salesmanagement.db
      - Admin__Email=${ADMIN_EMAIL}
      - Admin__Password=${ADMIN_PASSWORD}
      - AppSettings__Token=${APP_TOKEN}
    
    volumes:
      - sqlite_data:/data
    
    restart: unless-stopped
  
  seq:
    image:  datalust/seq:latest
    container_name: log-api-seq1
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin123
    ports:
      - 5341:5341
      - 8082:80
    
  frontend:
    container_name: sales-management-front
    build:
      context: ../SalesManagement.Front/sales-management
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:8080/api
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  sqlite_data:
    driver: local

